"""Load configuration from environment."""

import json
import logging
import os
from pathlib import Path

from dotenv import dotenv_values as _dotenv_values

from app.core.user_data import user_data_dir as _udd

_logger = logging.getLogger(__name__)

_PROJECT_APP_ROOT = Path(__file__).resolve().parent.parent.parent

# Merge defaults (committed) → user_data_dir .env (wins).
# Yields to values already present in os.environ (e.g. set by tests or CI).
_defaults_path = _PROJECT_APP_ROOT / "config" / "defaults.env"
_env_path = _udd() / ".env"
for _k, _v in {
    **_dotenv_values(_defaults_path),
    **_dotenv_values(_env_path),
}.items():
    if _k not in os.environ and _v is not None:
        os.environ[_k] = _v

# SSL certificate: prefer user_data_dir bundle, fall back to app root, then system CA store
_cert_file = _udd() / "certs" / "jira_ca_bundle.pem"
if not _cert_file.is_file():
    _cert_file = _PROJECT_APP_ROOT / "certs" / "jira_ca_bundle.pem"
JIRA_SSL_CERT: str | bool = str(_cert_file) if _cert_file.is_file() else True

JIRA_URL = os.getenv("JIRA_URL", "").rstrip("/")
JIRA_EMAIL = os.getenv("JIRA_EMAIL", "")
JIRA_API_TOKEN = os.getenv("JIRA_API_TOKEN", "")

# Optional: board ID (numeric). If unset, script will use first available board.
_board_id = os.getenv("JIRA_BOARD_ID", "").strip()
JIRA_BOARD_ID = int(_board_id) if _board_id.isdigit() else None

# Number of past sprints to include in report
_sprint_count = os.getenv("JIRA_SPRINT_COUNT", "10").strip()
JIRA_SPRINT_COUNT = int(_sprint_count) if _sprint_count.isdigit() else 10

# Optional: case-insensitive substring filter applied to sprint names before the count cap.
# When set, only sprints whose name contains this string are included.
JIRA_SPRINT_NAME_FILTER = os.getenv("JIRA_SPRINT_NAME_FILTER", "").strip()

# Optional: schema_name in config/jira_schema.json (CLI). When unset, default schema from file is used.
JIRA_SCHEMA_NAME = os.getenv("JIRA_SCHEMA_NAME", "").strip() or None

# Optional: Jira saved filter ID. When set, only issues matching this filter are included
# (filter's JQL is applied to sprint issues).
_filter_id = os.getenv("JIRA_FILTER_ID", "").strip()
JIRA_FILTER_ID = int(_filter_id) if _filter_id.isdigit() else None

# Optional: Jira project key (e.g. "MYPROJ"). Used to scope issue queries and shown in reports.
JIRA_PROJECT = os.getenv("JIRA_PROJECT", "").strip() or None

# DAU survey data is per-filter. Each filter in jira_filters.json carries a DAU_PATH key
# that points to a folder (absolute, under user_data_dir) containing:
#   <DAU_PATH>/original/   raw dau_*.json submissions
#   <DAU_PATH>/normalized/ auto-generated by normalize_dau_responses
#
# Resolution order for the active path:
#   1. DAU_PATH env var (set by the server when a filter is selected, or by the user)
#   2. The default filter's DAU_PATH in user_data_dir/config/jira_filters.json
#   3. Fallback: user_data_dir/data/dau/
# DAU_RESPONSES_DIR / DAU_NORMALIZED_DIR env vars, when set, override the derived paths.
_PROJECT_ROOT = _PROJECT_APP_ROOT


def _resolve_dau_path() -> Path | None:
    """Return the active DAU_PATH as an absolute Path, or None if not resolvable."""
    raw = os.getenv("DAU_PATH", "").strip()
    if not raw:
        # Prefer user_data_dir filters, fall back to legacy app-root filters
        for _filters_file in (
            _udd() / "config" / "jira_filters.json",
            _PROJECT_ROOT / "config" / "jira_filters.json",
        ):
            try:
                if _filters_file.is_file():
                    filters = json.loads(_filters_file.read_text(encoding="utf-8"))
                    if isinstance(filters, list):
                        default = next((f for f in filters if f.get("is_default")), None)
                        if default:
                            raw = ((default.get("params") or {}).get("DAU_PATH") or "").strip()
                    if raw:
                        break
            except (OSError, json.JSONDecodeError) as exc:
                _logger.warning("Could not read default DAU_PATH from %s: %s", _filters_file, exc)
    if not raw:
        return None
    p = Path(raw)
    if not p.is_absolute():
        # Relative paths are resolved against user_data_dir (new installs)
        p = _udd() / p
    return p


_dau_root = _resolve_dau_path()
_legacy_dau_root = _udd() / "data" / "dau"

DAU_RESPONSES_DIR: str = os.getenv(
    "DAU_RESPONSES_DIR",
    str((_dau_root / "original") if _dau_root else _legacy_dau_root),
)

DAU_NORMALIZED_DIR: str = os.getenv(
    "DAU_NORMALIZED_DIR",
    str((_dau_root / "normalized") if _dau_root else (_legacy_dau_root / "normalized")),
)

# AI Adoption metrics labels
# Umbrella label that marks an issue as AI-assisted. When unset/empty, classification
# falls back to checking AI_TOOL_LABELS / AI_ACTION_LABELS membership (see metrics.py).
AI_ASSISTED_LABEL = os.getenv("AI_ASSISTED_LABEL", "").strip()
# Comma-separated labels whose issues are excluded from the AI% denominator
AI_EXCLUDE_LABELS = [lbl.strip() for lbl in os.getenv("AI_EXCLUDE_LABELS", "").split(",") if lbl.strip()]
# Comma-separated labels identifying AI tools (e.g. AI_Tool_Copilot,AI_Tool_ChatGPT)
AI_TOOL_LABELS = [lbl.strip() for lbl in os.getenv("AI_TOOL_LABELS", "").split(",") if lbl.strip()]
# Comma-separated labels identifying AI use-cases (e.g. AI_Case_CodeGen,AI_Case_Review)
AI_ACTION_LABELS = [lbl.strip() for lbl in os.getenv("AI_ACTION_LABELS", "").split(",") if lbl.strip()]

# Project type: SCRUM or KANBAN (default: SCRUM)
_project_type_raw = os.getenv("PROJECT_TYPE", "SCRUM").strip().upper()
PROJECT_TYPE: str = _project_type_raw if _project_type_raw in ("SCRUM", "KANBAN") else "SCRUM"

# Local filter JQL forwarded by the generate handler when a saved filter has a jql field
# and JIRA_FILTER_ID is not set. Used as fallback in KANBAN data fetching.
JIRA_FILTER_JQL: str = os.getenv("JIRA_FILTER_JQL", "").strip()

# Estimation type: StoryPoints or JiraTickets (default: StoryPoints)
_estimation_type_raw = os.getenv("ESTIMATION_TYPE", "StoryPoints").strip()
ESTIMATION_TYPE: str = _estimation_type_raw if _estimation_type_raw in ("StoryPoints", "JiraTickets") else "StoryPoints"


# Metric toggle flags (all default to True)
def _env_bool(key: str, default: bool = True) -> bool:
    val = os.getenv(key, "").strip().lower()
    if not val:
        return default
    return val in ("1", "true", "yes")


# Sprint scope: when True, the active sprint is included in reports.
# Default False — active sprint is excluded.
JIRA_INCLUDE_ACTIVE_SPRINT: bool = _env_bool("JIRA_INCLUDE_ACTIVE_SPRINT", default=False)

REPORT_NAME: str = os.getenv("REPORT_NAME", "").strip()

METRIC_VELOCITY: bool = _env_bool("METRIC_VELOCITY")
METRIC_AI_ASSISTANCE_TREND: bool = _env_bool("METRIC_AI_ASSISTANCE_TREND")
METRIC_AI_USAGE_DETAILS: bool = _env_bool("METRIC_AI_USAGE_DETAILS")
METRIC_DAU: bool = _env_bool("METRIC_DAU")
METRIC_DAU_TREND: bool = _env_bool("METRIC_DAU_TREND")

_port_raw = os.getenv("PORT", "8080").strip()
SERVER_PORT: int = int(_port_raw) if _port_raw.isdigit() else 8080


def validate_config() -> list[str]:
    """Return list of validation errors; empty if config is valid."""
    errors = []
    if not JIRA_URL:
        errors.append("JIRA_URL is not set")
    if not JIRA_EMAIL:
        errors.append("JIRA_EMAIL is not set")
    if not JIRA_API_TOKEN:
        errors.append("JIRA_API_TOKEN is not set")
    if JIRA_BOARD_ID is None:
        errors.append("JIRA_BOARD_ID is not set")
    # Warn (not block) when raw JIRA_URL had trailing slash(es) — they were
    # silently stripped by the rstrip("/") above.
    raw_url = os.getenv("JIRA_URL", "")
    if raw_url and raw_url != raw_url.rstrip("/"):
        errors.append("JIRA_URL had a trailing slash (auto-stripped)")
    return errors
